<html>
    <head>
    </head>
    <body>
        <script>
            localStorage.clear();
        </script>
    </body>
</html>
<?php 
session_start();
session_unset();
header("Location:index.php");
?>